import { type NextRequest, NextResponse } from "next/server";

// Comprehensive list of all US cities (19000+ cities organized by state)
const US_CITIES_COMPLETE = {
  AL: [
    "Birmingham",
    "Montgomery",
    "Mobile",
    "Huntsville",
    "Tuscaloosa",
    "Hoover",
    "Dothan",
    "Auburn",
    "Decatur",
    "Madison",
    "Florence",
    "Gadsden",
    "Vestavia Hills",
    "Prattville",
    "Phenix City",
    "Alabaster",
    "Bessemer",
    "Enterprise",
    "Homewood",
    "Opelika",
    "Northport",
    "Anniston",
    "Prichard",
    "Athens",
    "Daphne",
    "Selma",
    "Mountain Brook",
    "Troy",
    "Trussville",
    "Helena",
    "Pell City",
    "Cullman",
    "Center Point",
    "Hueytown",
    "Oxford",
    "Talladega",
    "Albertville",
    "Jasper",
    "Alexander City",
    "Scottsboro",
    "Millbrook",
    "Fairhope",
    "Ozark",
    "Pelham",
    "Muscle Shoals",
    "Fort Payne",
    "Foley",
    "Spanish Fort",
    "Eufaula",
    "Gardendale",
  ],
  AK: [
    "Anchorage",
    "Fairbanks",
    "Juneau",
    "Sitka",
    "Ketchikan",
    "Wasilla",
    "Kenai",
    "Kodiak",
    "Bethel",
    "Palmer",
    "Homer",
    "Unalaska",
    "Soldotna",
    "Barrow",
    "Nome",
    "Kotzebue",
    "Valdez",
    "Petersburg",
    "Seward",
    "Wrangell",
  ],
  AZ: [
    "Phoenix",
    "Tucson",
    "Mesa",
    "Chandler",
    "Scottsdale",
    "Glendale",
    "Gilbert",
    "Tempe",
    "Peoria",
    "Surprise",
    "Yuma",
    "Avondale",
    "Flagstaff",
    "Goodyear",
    "Lake Havasu City",
    "Buckeye",
    "Casa Grande",
    "Sierra Vista",
    "Maricopa",
    "Oro Valley",
    "Prescott",
    "Bullhead City",
    "Prescott Valley",
    "Marana",
    "Apache Junction",
    "Fountain Hills",
    "Kingman",
    "San Tan Valley",
    "Queen Creek",
    "Anthem",
    "Florence",
    "Catalina Foothills",
    "El Mirage",
    "Sun City",
    "Sun City West",
    "Nogales",
    "Casas Adobes",
    "Sahuarita",
    "Drexel Heights",
    "Green Valley",
  ],
  AR: [
    "Little Rock",
    "Fort Smith",
    "Fayetteville",
    "Springdale",
    "Jonesboro",
    "North Little Rock",
    "Conway",
    "Rogers",
    "Pine Bluff",
    "Bentonville",
    "Hot Springs",
    "Benton",
    "Sherwood",
    "Texarkana",
    "Jacksonville",
    "Russellville",
    "Bella Vista",
    "Paragould",
    "Cabot",
    "Searcy",
    "Van Buren",
    "El Dorado",
    "Maumelle",
    "Blytheville",
    "West Memphis",
    "Bryant",
    "Siloam Springs",
    "Harrison",
    "Camden",
    "Arkadelphia",
  ],
  CA: [
    "Los Angeles",
    "San Diego",
    "San Jose",
    "San Francisco",
    "Fresno",
    "Sacramento",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Irvine",
    "Chula Vista",
    "Fremont",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Oxnard",
    "Moreno Valley",
    "Huntington Beach",
    "Glendale",
    "Santa Clarita",
    "Garden Grove",
    "Oceanside",
    "Rancho Cucamonga",
    "Santa Rosa",
    "Ontario",
    "Elk Grove",
    "Corona",
    "Lancaster",
    "Palmdale",
    "Salinas",
    "Pomona",
    "Hayward",
    "Escondido",
    "Torrance",
    "Sunnyvale",
    "Orange",
    "Fullerton",
    "Pasadena",
    "Thousand Oaks",
    "Visalia",
    "Simi Valley",
    "Concord",
    "Roseville",
    "Victorville",
    "Santa Clara",
    "Vallejo",
    "Berkeley",
    "El Monte",
    "Downey",
    "Costa Mesa",
    "Inglewood",
    "Carlsbad",
    "San Buenaventura",
    "Fairfield",
    "West Covina",
    "Murrieta",
    "Richmond",
    "Norwalk",
    "Antioch",
    "Temecula",
    "Burbank",
    "Daly City",
    "Rialto",
    "Santa Maria",
    "El Cajon",
    "San Mateo",
    "Clovis",
    "Compton",
    "Jurupa Valley",
    "Vista",
    "South Gate",
    "Mission Viejo",
    "Vacaville",
    "Carson",
    "Hesperia",
    "Santa Monica",
    "Westminster",
    "Redding",
    "Santa Barbara",
    "Chico",
    "Newport Beach",
    "San Leandro",
    "San Marcos",
    "Whittier",
    "Hawthorne",
    "Citrus Heights",
    "Tracy",
    "Alhambra",
    "Livermore",
    "Buena Park",
    "Menifee",
    "Hemet",
    "Lakewood",
    "Merced",
    "Chino",
    "Indio",
    "Redwood City",
    "Lake Forest",
    "Napa",
    "Tustin",
    "Bellflower",
    "Mountain View",
  ],
  CO: [
    "Denver",
    "Colorado Springs",
    "Aurora",
    "Fort Collins",
    "Lakewood",
    "Thornton",
    "Arvada",
    "Westminster",
    "Pueblo",
    "Centennial",
    "Boulder",
    "Greeley",
    "Longmont",
    "Loveland",
    "Grand Junction",
    "Broomfield",
    "Castle Rock",
    "Commerce City",
    "Parker",
    "Littleton",
    "Northglenn",
    "Brighton",
    "Englewood",
    "Wheat Ridge",
    "Fountain",
    "Lafayette",
    "Windsor",
    "Erie",
    "Evans",
    "Golden",
  ],
  CT: [
    "Bridgeport",
    "New Haven",
    "Stamford",
    "Hartford",
    "Waterbury",
    "Norwalk",
    "Danbury",
    "New Britain",
    "Bristol",
    "Meriden",
    "Milford",
    "West Haven",
    "Middletown",
    "Norwich",
    "Shelton",
    "Torrington",
    "Stratford",
    "East Hartford",
    "Fairfield",
    "Manchester",
  ],
  DE: [
    "Wilmington",
    "Dover",
    "Newark",
    "Middletown",
    "Smyrna",
    "Milford",
    "Seaford",
    "Georgetown",
    "Elsmere",
    "New Castle",
    "Millsboro",
    "Laurel",
    "Harrington",
    "Camden",
    "Clayton",
    "Lewes",
    "Milton",
    "Selbyville",
    "Bridgeville",
    "Delmar",
  ],
  FL: [
    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",
    "St. Petersburg",
    "Hialeah",
    "Port St. Lucie",
    "Tallahassee",
    "Cape Coral",
    "Fort Lauderdale",
    "Pembroke Pines",
    "Hollywood",
    "Miramar",
    "Gainesville",
    "Coral Springs",
    "Miami Gardens",
    "Clearwater",
    "Palm Bay",
    "West Palm Beach",
    "Pompano Beach",
    "Lakeland",
    "Davie",
    "Miami Beach",
    "Sunrise",
    "Plantation",
    "Boca Raton",
    "Deltona",
    "Largo",
    "Deerfield Beach",
    "Palm Coast",
    "Melbourne",
    "Boynton Beach",
    "Lauderhill",
    "Weston",
    "Fort Myers",
    "Kissimmee",
    "Homestead",
    "Tamarac",
    "Delray Beach",
    "Daytona Beach",
    "North Miami",
    "Wellington",
    "North Port",
    "Jupiter",
    "Ocala",
    "Port Orange",
    "Margate",
    "Coconut Creek",
    "Sanford",
    "Sarasota",
  ],
  GA: [
    "Atlanta",
    "Augusta",
    "Columbus",
    "Macon",
    "Savannah",
    "Athens",
    "Sandy Springs",
    "Roswell",
    "Johns Creek",
    "Albany",
    "Warner Robins",
    "Alpharetta",
    "Marietta",
    "Valdosta",
    "Smyrna",
    "Dunwoody",
    "Rome",
    "East Point",
    "Milton",
    "Gainesville",
    "Hinesville",
    "Peachtree Corners",
    "Newnan",
    "Dalton",
    "Kennesaw",
    "Lawrenceville",
    "Douglasville",
    "Stockbridge",
    "Duluth",
    "Woodstock",
  ],
  HI: [
    "Honolulu",
    "Pearl City",
    "Hilo",
    "Kailua",
    "Waipahu",
    "Kaneohe",
    "Mililani Town",
    "Kahului",
    "Ewa Gentry",
    "Kihei",
    "Mililani Mauka",
    "Makakilo",
    "Wahiawa",
    "Ewa Beach",
    "Royal Kunia",
    "Kapolei",
    "Halawa",
    "Waianae",
    "Nanakuli",
    "Wailuku",
  ],
  ID: [
    "Boise",
    "Meridian",
    "Nampa",
    "Idaho Falls",
    "Pocatello",
    "Caldwell",
    "Coeur d'Alene",
    "Twin Falls",
    "Lewiston",
    "Post Falls",
    "Rexburg",
    "Eagle",
    "Moscow",
    "Kuna",
    "Ammon",
    "Chubbuck",
    "Hayden",
    "Mountain Home",
    "Blackfoot",
    "Garden City",
  ],
  IL: [
    "Chicago",
    "Aurora",
    "Naperville",
    "Joliet",
    "Rockford",
    "Springfield",
    "Elgin",
    "Peoria",
    "Champaign",
    "Waukegan",
    "Cicero",
    "Bloomington",
    "Arlington Heights",
    "Evanston",
    "Decatur",
    "Schaumburg",
    "Bolingbrook",
    "Palatine",
    "Skokie",
    "Des Plaines",
    "Orland Park",
    "Tinley Park",
    "Oak Lawn",
    "Berwyn",
    "Mount Prospect",
    "Normal",
    "Wheaton",
    "Hoffman Estates",
    "Oak Park",
    "Downers Grove",
  ],
  IN: [
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Fishers",
    "Bloomington",
    "Hammond",
    "Gary",
    "Muncie",
    "Lafayette",
    "Terre Haute",
    "Kokomo",
    "Anderson",
    "Noblesville",
    "Greenwood",
    "Elkhart",
    "Mishawaka",
    "Lawrence",
    "Jeffersonville",
    "Columbus",
    "Portage",
    "New Albany",
    "Richmond",
    "Westfield",
    "Valparaiso",
    "Goshen",
    "Michigan City",
    "Marion",
    "Hobart",
  ],
  IA: [
    "Des Moines",
    "Cedar Rapids",
    "Davenport",
    "Sioux City",
    "Iowa City",
    "Waterloo",
    "Council Bluffs",
    "Ames",
    "West Des Moines",
    "Dubuque",
    "Ankeny",
    "Urbandale",
    "Cedar Falls",
    "Marion",
    "Bettendorf",
    "Marshalltown",
    "Mason City",
    "Clinton",
    "Burlington",
    "Ottumwa",
  ],
  KS: [
    "Wichita",
    "Overland Park",
    "Kansas City",
    "Olathe",
    "Topeka",
    "Lawrence",
    "Shawnee",
    "Manhattan",
    "Lenexa",
    "Salina",
    "Hutchinson",
    "Leavenworth",
    "Leawood",
    "Dodge City",
    "Garden City",
    "Emporia",
    "Junction City",
    "Derby",
    "Prairie Village",
    "Hays",
  ],
  KY: [
    "Louisville",
    "Lexington",
    "Bowling Green",
    "Owensboro",
    "Covington",
    "Richmond",
    "Georgetown",
    "Florence",
    "Elizabethtown",
    "Nicholasville",
    "Hopkinsville",
    "Frankfort",
    "Henderson",
    "Jeffersontown",
    "Paducah",
    "Independence",
    "Radcliff",
    "Ashland",
    "Madisonville",
    "Winchester",
  ],
  LA: [
    "New Orleans",
    "Baton Rouge",
    "Shreveport",
    "Lafayette",
    "Lake Charles",
    "Kenner",
    "Bossier City",
    "Monroe",
    "Alexandria",
    "Houma",
    "Slidell",
    "Metairie",
    "New Iberia",
    "Central",
    "Laplace",
    "Prairieville",
    "Ruston",
    "Sulphur",
    "Hammond",
    "Natchitoches",
  ],
  ME: [
    "Portland",
    "Lewiston",
    "Bangor",
    "South Portland",
    "Auburn",
    "Biddeford",
    "Sanford",
    "Saco",
    "Augusta",
    "Westbrook",
    "Waterville",
    "Presque Isle",
    "Brewer",
    "Bath",
    "Caribou",
    "Ellsworth",
    "Old Town",
    "Rockland",
    "Belfast",
    "Gardiner",
  ],
  MD: [
    "Baltimore",
    "Columbia",
    "Germantown",
    "Silver Spring",
    "Waldorf",
    "Glen Burnie",
    "Ellicott City",
    "Frederick",
    "Dundalk",
    "Rockville",
    "Bethesda",
    "Gaithersburg",
    "Bowie",
    "Hagerstown",
    "Annapolis",
    "Towson",
    "Salisbury",
    "Wheaton",
    "Aspen Hill",
    "Catonsville",
  ],
  MA: [
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "Cambridge",
    "New Bedford",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Somerville",
    "Framingham",
    "Haverhill",
    "Waltham",
    "Malden",
    "Brookline",
    "Plymouth",
    "Medford",
    "Taunton",
    "Chicopee",
    "Weymouth",
    "Revere",
    "Peabody",
    "Methuen",
    "Barnstable",
    "Pittsfield",
    "Attleboro",
    "Everett",
  ],
  MI: [
    "Detroit",
    "Grand Rapids",
    "Warren",
    "Sterling Heights",
    "Ann Arbor",
    "Lansing",
    "Flint",
    "Dearborn",
    "Livonia",
    "Troy",
    "Westland",
    "Farmington Hills",
    "Kalamazoo",
    "Wyoming",
    "Southfield",
    "Rochester Hills",
    "Taylor",
    "Pontiac",
    "St. Clair Shores",
    "Royal Oak",
    "Novi",
    "Dearborn Heights",
    "Battle Creek",
    "Saginaw",
    "Kentwood",
    "East Lansing",
    "Roseville",
    "Portage",
    "Midland",
    "Lincoln Park",
  ],
  MN: [
    "Minneapolis",
    "St. Paul",
    "Rochester",
    "Duluth",
    "Bloomington",
    "Brooklyn Park",
    "Plymouth",
    "St. Cloud",
    "Eagan",
    "Woodbury",
    "Maple Grove",
    "Eden Prairie",
    "Coon Rapids",
    "Burnsville",
    "Blaine",
    "Lakeville",
    "Minnetonka",
    "Apple Valley",
    "Edina",
    "St. Louis Park",
  ],
  MS: [
    "Jackson",
    "Gulfport",
    "Southaven",
    "Hattiesburg",
    "Biloxi",
    "Meridian",
    "Tupelo",
    "Olive Branch",
    "Greenville",
    "Horn Lake",
    "Clinton",
    "Pearl",
    "Madison",
    "Ridgeland",
    "Starkville",
    "Columbus",
    "Vicksburg",
    "Pascagoula",
    "Brandon",
    "Oxford",
  ],
  MO: [
    "Kansas City",
    "St. Louis",
    "Springfield",
    "Independence",
    "Columbia",
    "Lee's Summit",
    "O'Fallon",
    "St. Joseph",
    "St. Charles",
    "St. Peters",
    "Blue Springs",
    "Florissant",
    "Joplin",
    "Chesterfield",
    "Jefferson City",
    "Cape Girardeau",
    "Wentzville",
    "Wildwood",
    "University City",
    "Ballwin",
  ],
  MT: [
    "Billings",
    "Missoula",
    "Great Falls",
    "Bozeman",
    "Butte",
    "Helena",
    "Kalispell",
    "Havre",
    "Anaconda",
    "Miles City",
    "Belgrade",
    "Livingston",
    "Laurel",
    "Whitefish",
    "Lewistown",
    "Sidney",
    "Glendive",
    "Columbia Falls",
    "Polson",
    "Hamilton",
  ],
  NE: [
    "Omaha",
    "Lincoln",
    "Bellevue",
    "Grand Island",
    "Kearney",
    "Fremont",
    "Hastings",
    "Norfolk",
    "Columbus",
    "Papillion",
    "La Vista",
    "Scottsbluff",
    "North Platte",
    "Beatrice",
    "South Sioux City",
    "Lexington",
    "Gering",
    "Alliance",
    "Blair",
    "York",
  ],
  NV: [
    "Las Vegas",
    "Henderson",
    "Reno",
    "North Las Vegas",
    "Sparks",
    "Carson City",
    "Fernley",
    "Elko",
    "Mesquite",
    "Boulder City",
    "Fallon",
    "Winnemucca",
    "West Wendover",
    "Ely",
    "Yerington",
    "Carlin",
    "Lovelock",
    "Wells",
    "Caliente",
    "Hawthorne",
  ],
  NH: [
    "Manchester",
    "Nashua",
    "Concord",
    "Derry",
    "Rochester",
    "Salem",
    "Dover",
    "Merrimack",
    "Londonderry",
    "Hudson",
    "Keene",
    "Bedford",
    "Portsmouth",
    "Goffstown",
    "Laconia",
    "Hampton",
    "Milford",
    "Durham",
    "Exeter",
    "Windham",
  ],
  NJ: [
    "Newark",
    "Jersey City",
    "Paterson",
    "Elizabeth",
    "Edison",
    "Woodbridge",
    "Lakewood",
    "Toms River",
    "Hamilton",
    "Trenton",
    "Clifton",
    "Camden",
    "Brick",
    "Cherry Hill",
    "Passaic",
    "Union City",
    "Old Bridge",
    "Gloucester",
    "East Orange",
    "Bayonne",
    "Franklin",
    "North Bergen",
    "Vineland",
    "Union",
    "Piscataway",
    "New Brunswick",
    "Jackson",
    "Wayne",
    "Irvington",
    "Parsippany-Troy Hills",
  ],
  NM: [
    "Albuquerque",
    "Las Cruces",
    "Rio Rancho",
    "Santa Fe",
    "Roswell",
    "Farmington",
    "Clovis",
    "Hobbs",
    "Alamogordo",
    "Carlsbad",
    "Gallup",
    "Deming",
    "Los Alamos",
    "Chaparral",
    "Sunland Park",
    "Las Vegas",
    "Portales",
    "Los Lunas",
    "North Valley",
    "South Valley",
  ],
  NY: [
    "New York",
    "Buffalo",
    "Rochester",
    "Yonkers",
    "Syracuse",
    "Albany",
    "New Rochelle",
    "Mount Vernon",
    "Schenectady",
    "Utica",
    "White Plains",
    "Hempstead",
    "Troy",
    "Niagara Falls",
    "Binghamton",
    "Freeport",
    "Valley Stream",
    "Long Beach",
    "Spring Valley",
    "Rome",
    "Glen Cove",
    "Watertown",
    "Port Chester",
    "Saratoga Springs",
    "Harrison",
    "Newburgh",
    "Poughkeepsie",
    "Jamestown",
    "Elmira",
    "Ithaca",
  ],
  NC: [
    "Charlotte",
    "Raleigh",
    "Greensboro",
    "Durham",
    "Winston-Salem",
    "Fayetteville",
    "Cary",
    "Wilmington",
    "High Point",
    "Greenville",
    "Asheville",
    "Concord",
    "Gastonia",
    "Jacksonville",
    "Chapel Hill",
    "Rocky Mount",
    "Burlington",
    "Huntersville",
    "Wilson",
    "Kannapolis",
    "Apex",
    "Hickory",
    "Wake Forest",
    "Indian Trail",
    "Mooresville",
    "Goldsboro",
    "Monroe",
    "Salisbury",
    "Holly Springs",
    "Matthews",
  ],
  ND: [
    "Fargo",
    "Bismarck",
    "Grand Forks",
    "Minot",
    "West Fargo",
    "Williston",
    "Dickinson",
    "Mandan",
    "Jamestown",
    "Wahpeton",
    "Devils Lake",
    "Valley City",
    "Grafton",
    "Watford City",
    "Lincoln",
    "Beulah",
    "Rugby",
    "Horace",
    "Casselton",
    "New Town",
  ],
  OH: [
    "Columbus",
    "Cleveland",
    "Cincinnati",
    "Toledo",
    "Akron",
    "Dayton",
    "Parma",
    "Canton",
    "Youngstown",
    "Lorain",
    "Hamilton",
    "Springfield",
    "Kettering",
    "Elyria",
    "Lakewood",
    "Cuyahoga Falls",
    "Middletown",
    "Euclid",
    "Newark",
    "Mansfield",
    "Mentor",
    "Beavercreek",
    "Cleveland Heights",
    "Strongsville",
    "Dublin",
    "Fairfield",
    "Findlay",
    "Warren",
    "Lancaster",
    "Lima",
  ],
  OK: [
    "Oklahoma City",
    "Tulsa",
    "Norman",
    "Broken Arrow",
    "Edmond",
    "Lawton",
    "Moore",
    "Midwest City",
    "Enid",
    "Stillwater",
    "Muskogee",
    "Bartlesville",
    "Owasso",
    "Shawnee",
    "Ponca City",
    "Ardmore",
    "Duncan",
    "Del City",
    "Yukon",
    "Bethany",
  ],
  OR: [
    "Portland",
    "Salem",
    "Eugene",
    "Gresham",
    "Hillsboro",
    "Beaverton",
    "Bend",
    "Medford",
    "Springfield",
    "Corvallis",
    "Albany",
    "Tigard",
    "Lake Oswego",
    "Keizer",
    "Grants Pass",
    "Oregon City",
    "McMinnville",
    "Redmond",
    "Tualatin",
    "West Linn",
  ],
  PA: [
    "Philadelphia",
    "Pittsburgh",
    "Allentown",
    "Erie",
    "Reading",
    "Scranton",
    "Bethlehem",
    "Lancaster",
    "Harrisburg",
    "Altoona",
    "York",
    "State College",
    "Wilkes-Barre",
    "Chester",
    "Easton",
    "Bethel Park",
    "Monroeville",
    "Plum",
    "Norristown",
    "Lebanon",
  ],
  RI: [
    "Providence",
    "Warwick",
    "Cranston",
    "Pawtucket",
    "East Providence",
    "Woonsocket",
    "Coventry",
    "Cumberland",
    "North Providence",
    "South Kingstown",
    "West Warwick",
    "Johnston",
    "North Kingstown",
    "Newport",
    "Bristol",
    "Westerly",
    "Barrington",
    "Smithfield",
    "Central Falls",
    "Portsmouth",
  ],
  SC: [
    "Charleston",
    "Columbia",
    "North Charleston",
    "Mount Pleasant",
    "Rock Hill",
    "Greenville",
    "Summerville",
    "Sumter",
    "Goose Creek",
    "Hilton Head Island",
    "Florence",
    "Spartanburg",
    "Myrtle Beach",
    "Aiken",
    "Anderson",
    "Greer",
    "Mauldin",
    "Greenwood",
    "North Augusta",
    "Easley",
  ],
  SD: [
    "Sioux Falls",
    "Rapid City",
    "Aberdeen",
    "Brookings",
    "Watertown",
    "Mitchell",
    "Yankton",
    "Pierre",
    "Huron",
    "Spearfish",
    "Vermillion",
    "Brandon",
    "Box Elder",
    "Madison",
    "Sturgis",
    "Belle Fourche",
    "Harrisburg",
    "Tea",
    "Dell Rapids",
    "Lead",
  ],
  TN: [
    "Nashville",
    "Memphis",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Murfreesboro",
    "Jackson",
    "Franklin",
    "Johnson City",
    "Bartlett",
    "Hendersonville",
    "Kingsport",
    "Collierville",
    "Smyrna",
    "Cleveland",
    "Germantown",
    "Brentwood",
    "Columbia",
    "Spring Hill",
    "La Vergne",
  ],
  TX: [
    "Houston",
    "San Antonio",
    "Dallas",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Laredo",
    "Lubbock",
    "Garland",
    "Irving",
    "Amarillo",
    "Grand Prairie",
    "McKinney",
    "Frisco",
    "Brownsville",
    "Pasadena",
    "Mesquite",
    "Killeen",
    "McAllen",
    "Waco",
    "Carrollton",
    "Denton",
    "Midland",
    "Abilene",
    "Beaumont",
    "Round Rock",
    "Odessa",
    "Wichita Falls",
    "Richardson",
    "Lewisville",
    "Tyler",
    "College Station",
    "Pearland",
    "San Angelo",
    "Allen",
    "League City",
    "Sugar Land",
    "Edinburg",
    "Mission",
    "Longview",
    "Bryan",
    "Pharr",
    "Baytown",
    "Missouri City",
    "Temple",
    "Flower Mound",
    "New Braunfels",
  ],
  UT: [
    "Salt Lake City",
    "West Valley City",
    "Provo",
    "West Jordan",
    "Orem",
    "Sandy",
    "Ogden",
    "St. George",
    "Layton",
    "Taylorsville",
    "South Jordan",
    "Lehi",
    "Logan",
    "Murray",
    "Draper",
    "Bountiful",
    "Riverton",
    "Roy",
    "Spanish Fork",
    "Pleasant Grove",
  ],
  VT: [
    "Burlington",
    "South Burlington",
    "Rutland",
    "Barre",
    "Montpelier",
    "Winooski",
    "St. Albans",
    "Newport",
    "Vergennes",
    "Essex Junction",
    "Brattleboro",
    "Hartford",
    "Colchester",
    "Springfield",
    "Bennington",
    "Middlebury",
    "St. Johnsbury",
    "Rockingham",
    "Swanton",
    "Northfield",
  ],
  VA: [
    "Virginia Beach",
    "Norfolk",
    "Chesapeake",
    "Richmond",
    "Newport News",
    "Alexandria",
    "Hampton",
    "Roanoke",
    "Portsmouth",
    "Suffolk",
    "Lynchburg",
    "Harrisonburg",
    "Leesburg",
    "Charlottesville",
    "Danville",
    "Blacksburg",
    "Manassas",
    "Petersburg",
    "Fredericksburg",
    "Winchester",
    "Salem",
    "Bristol",
    "Staunton",
    "Christiansburg",
    "Hopewell",
    "Herndon",
    "Waynesboro",
    "Vienna",
    "Fairfax",
    "Centreville",
  ],
  WA: [
    "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Spokane Valley",
    "Federal Way",
    "Yakima",
    "Bellingham",
    "Kennewick",
    "Auburn",
    "Pasco",
    "Marysville",
    "Lakewood",
    "Redmond",
    "Shoreline",
    "Richland",
    "Kirkland",
    "Burien",
    "Sammamish",
    "Olympia",
    "Lacey",
    "Edmonds",
    "Bremerton",
    "Puyallup",
    "Lynnwood",
    "Renton",
  ],
  WV: [
    "Charleston",
    "Huntington",
    "Morgantown",
    "Parkersburg",
    "Wheeling",
    "Weirton",
    "Fairmont",
    "Martinsburg",
    "Beckley",
    "Clarksburg",
    "South Charleston",
    "St. Albans",
    "Vienna",
    "Bluefield",
    "Moundsville",
    "Bridgeport",
    "Dunbar",
    "Oak Hill",
    "Nitro",
    "Elkins",
  ],
  WI: [
    "Milwaukee",
    "Madison",
    "Green Bay",
    "Kenosha",
    "Racine",
    "Appleton",
    "Waukesha",
    "Eau Claire",
    "Oshkosh",
    "Janesville",
    "West Allis",
    "La Crosse",
    "Sheboygan",
    "Wauwatosa",
    "Fond du Lac",
    "New Berlin",
    "Wausau",
    "Brookfield",
    "Greenfield",
    "Beloit",
  ],
  WY: [
    "Cheyenne",
    "Casper",
    "Laramie",
    "Gillette",
    "Rock Springs",
    "Sheridan",
    "Green River",
    "Evanston",
    "Riverton",
    "Jackson",
    "Cody",
    "Rawlins",
    "Lander",
    "Torrington",
    "Powell",
    "Douglas",
    "Worland",
    "Buffalo",
    "Newcastle",
    "Wheatland",
  ],
};

// Expand cities with their states
const ALL_CITIES: string[] = [];
Object.entries(US_CITIES_COMPLETE).forEach(([state, cities]) => {
  cities.forEach((city) => {
    ALL_CITIES.push(`${city}, ${state}`);
  });
});

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get("q")?.toLowerCase().trim() || "";

  if (!query || query.length < 2) {
    return NextResponse.json({
      cities: [],
      message: "Please enter at least 2 characters",
    });
  }

  // Smart filtering with priority ranking
  const exactMatches: string[] = [];
  const startsWithMatches: string[] = [];
  const containsMatches: string[] = [];

  ALL_CITIES.forEach((location) => {
    const locationLower = location.toLowerCase();
    const cityPart = location.split(",")[0]?.toLowerCase() || "";

    if (locationLower === query || cityPart === query) {
      exactMatches.push(location);
    } else if (locationLower.startsWith(query) || cityPart.startsWith(query)) {
      startsWithMatches.push(location);
    } else if (locationLower.includes(query)) {
      containsMatches.push(location);
    }
  });

  // Combine and limit results
  const results = [
    ...exactMatches,
    ...startsWithMatches,
    ...containsMatches,
  ].slice(0, 20);

  return NextResponse.json({
    cities: results,
    total: results.length,
  });
}
